## Introduction

This notebook explores the following datasets gathered from the Kaggle website.

- ``short_video_engagement.csv``
- ``tiktok_dataset.csv``
- ``youtube_data.csv``

We will be using these datasets to look into how video length affects different forms of engagement on social media platforms including Instagram, YouTube, and TikTok. Our motivation for this project comes from our interest in how short-form content has dominated the internet.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
shortvids = pd.read_csv('data/short_video_engagement.csv')
print('Shape:', shortvids.shape)
shortvids.head()

Shape: (17654, 12)

,views,likes,comments,watch_duration,shares,title_length,description_length,edge_intensity,color_histogram,spectral_entropy,audio_intensity,engagement_score
0,47,11,4,74.340181,0,18,878,0.436661,0.676880,0.524134,0.224402,1
1,55,14,2,86.547617,1,89,46,0.269328,0.376931,0.519303,0.044861,1
2,42,8,1,54.707006,0,97,568,0.136938,0.810070,0.636209,0.369313,1
3,52,11,3,79.213670,1,73,430,0.376898,0.873595,0.428849,0.220346,1
4,58,5,3,48.211898,0,62,339,0.380682,0.357269,0.580513,0.350787,0

In [7]:
shortvids.describe()

,views,likes,comments,watch_duration,shares,title_length,description_length,edge_intensity,color_histogram,spectral_entropy,audio_intensity,engagement_score
count,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000,17654.000000
mean,49.959839,9.990937,2.495015,69.892957,0.498641,52.084797,511.092274,0.284590,0.715260,0.498195,0.501370,0.786451
std,7.032334,3.153672,1.559069,14.679226,0.698440,27.378327,283.124829,0.158514,0.158568,0.100722,0.288421,0.409824
min,26.000000,0.000000,0.000000,3.055472,0.000000,5.000000,20.000000,0.002205,0.112293,0.059579,0.000018,0.000000
25%,45.000000,8.000000,1.000000,59.866590,0.000000,29.000000,266.000000,0.160926,0.611448,0.430547,0.248718,1.000000
50%,50.000000,10.000000,2.000000,70.090021,0.000000,52.000000,512.000000,0.263152,0.736160,0.498227,0.500815,1.000000
75%,55.000000,12.000000,3.000000,80.129476,1.000000,76.000000,759.000000,0.387945,0.839009,0.565591,0.750432,1.000000
max,76.000000,24.000000,11.000000,100.000000,5.000000,99.000000,999.000000,0.890822,0.997619,0.921937,0.999995,1.000000

In [8]:
shortvids.columns

Index(['views', 'likes', 'comments', 'watch_duration', 'shares',
       'title_length', 'description_length', 'edge_intensity',
       'color_histogram', 'spectral_entropy', 'audio_intensity',
       'engagement_score'],
      dtype='object')

In [19]:
shortvids.dtypes

views                   int64
likes                   int64
comments                int64
watch_duration        float64
shares                  int64
title_length            int64
description_length      int64
engagement_score        int64
dtype: object

Since we're not interested in ``edge_intensity``, ``color_histogram``, ``spectral_entropy``, ``audio_intensity`` we will drop these columns.

In [9]:
shortvids = shortvids.drop(columns = ['edge_intensity', 'color_histogram', 'spectral_entropy', 'audio_intensity'])

In [11]:
# confirm that the columns are dropped
print(shortvids.shape)
shortvids.head()

(17654, 8)

,views,likes,comments,watch_duration,shares,title_length,description_length,engagement_score
0,47,11,4,74.340181,0,18,878,1
1,55,14,2,86.547617,1,89,46,1
2,42,8,1,54.707006,0,97,568,1
3,52,11,3,79.213670,1,73,430,1
4,58,5,3,48.211898,0,62,339,0

In [12]:
# check for nulls
shortvids.isna().sum().sum()

np.int64(0)

Luckily, there are no null values in any columns, meaning that our data is clean and ready for visualization.

### TikTok Dataset

In [4]:
tiktok = pd.read_csv('data/tiktok_dataset.csv')
print('Shape:', tiktok.shape)
tiktok.head()

Shape: (19382, 12)

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0

In [13]:
tiktok.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
count,19382.000000,1.938200e+04,19382.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000
mean,9691.500000,5.627454e+09,32.421732,254708.558688,84304.636030,16735.248323,1049.429627,349.312146
std,5595.245794,2.536440e+09,16.229967,322893.280814,133420.546814,32036.174350,2004.299894,799.638865
min,1.000000,1.234959e+09,5.000000,20.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.430417e+09,18.000000,4942.500000,810.750000,115.000000,7.000000,1.000000
50%,9691.500000,5.618664e+09,32.000000,9954.500000,3403.500000,717.000000,46.000000,9.000000
75%,14536.750000,7.843960e+09,47.000000,504327.000000,125020.000000,18222.000000,1156.250000,292.000000
max,19382.000000,9.999873e+09,60.000000,999817.000000,657830.000000,256130.000000,14994.000000,9599.000000

In [14]:
tiktok.columns

Index(['#', 'claim_status', 'video_id', 'video_duration_sec',
       'video_transcription_text', 'verified_status', 'author_ban_status',
       'video_view_count', 'video_like_count', 'video_share_count',
       'video_download_count', 'video_comment_count'],
      dtype='object')

In [18]:
tiktok.dtypes

#                             int64
claim_status                 object
video_id                      int64
video_duration_sec            int64
video_transcription_text     object
verified_status              object
author_ban_status            object
video_view_count            float64
video_like_count            float64
video_share_count           float64
video_download_count        float64
video_comment_count         float64
dtype: object

### YouTube Dataset

In [6]:
yt = pd.read_csv('data/youtube_data.csv')
print('Shape:', yt.shape)
yt.head()

Shape: (600, 13)

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg
1,ypicIkaiViM,AI & future of workforce: Andrew Yang on how t...,"Andrew Yang, Forward Party co-chair and former...",2025-06-18T12:39:53Z,UCrp_UI8XtuYfpiqluWLD7Lw,CNBC Television,"['Squawk Box U.S.', 'CNBC', 'business news', '...",25,289626.0,3393.0,1240.0,PT7M50S,https://i.ytimg.com/vi/ypicIkaiViM/default.jpg
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg

In [15]:
yt.describe()

       category_id    view_count    like_count  comment_count
count   600.000000  6.000000e+02  6.000000e+02     600.000000
mean     24.903333  8.080299e+06  2.174646e+05    1970.144781
std       4.863477  2.455377e+07  5.074207e+05    4421.455908
min       1.000000  3.120000e+02  0.000000e+00       0.000000
25%      22.000000  8.150100e+04  1.646000e+03      13.000000
50%      27.000000  9.587180e+05  2.214900e+04     252.500000
75%      28.000000  5.991357e+06  2.174646e+05    1802.500000
max      30.000000  3.437590e+08  4.421091e+06   40241.000000

In [16]:
yt.columns

Index(['video_id', 'title', 'description', 'published_date', 'channel_id',
       'channel_title', 'tags', 'category_id', 'view_count', 'like_count',
       'comment_count', 'duration', 'thumbnail'],
      dtype='object')

In [17]:
yt.dtypes

video_id           object
title              object
description        object
published_date     object
channel_id         object
channel_title      object
tags               object
category_id         int64
view_count        float64
like_count        float64
comment_count     float64
duration           object
thumbnail          object
dtype: object