<a href="https://colab.research.google.com/github/keil4ni/151r-proj/blob/main/Tiktok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [19]:
tiktok = pd.read_csv("tiktok_dataset.csv")

In [20]:
tiktok.columns

Index(['#', 'claim_status', 'video_id', 'video_duration_sec',
       'video_transcription_text', 'verified_status', 'author_ban_status',
       'video_view_count', 'video_like_count', 'video_share_count',
       'video_download_count', 'video_comment_count'],
      dtype='object')

In [21]:
tiktok_std = tiktok.rename(columns={
    "video_view_count": "views",
    "video_like_count": "likes",
    "video_duration_sec": "duration"
})[["video_id", "views", "likes", "duration"]]

In [22]:
tiktok_clean = tiktok_std.dropna()
tiktok_clean

         video_id     views     likes  duration
0      7017666017  343296.0   19425.0        59
1      4014381136  140877.0   77355.0        32
2      9859838091  902185.0   97690.0        31
3      1866847991  437506.0  239954.0        25
4      7105231098   56167.0   34987.0        19
...           ...       ...       ...       ...
19079  1492320297    6067.0     423.0        49
19080  9841347807    2973.0     820.0        23
19081  8024379946     734.0     102.0        50
19082  7425795014    3394.0     655.0         8
19083  4094655375    5034.0     815.0        58

[19084 rows x 4 columns]

In [23]:
tiktok_clean["engagement_rate"] = tiktok_clean["likes"] / tiktok_clean["views"]
tiktok_clean["engagement_rate"] = tiktok_clean["engagement_rate"] * 100
# standardizing
tiktok_clean["log_views"] = np.log1p(tiktok_clean["views"])
tiktok_clean["log_likes"] = np.log1p(tiktok_clean["likes"])

/tmp/ipykernel_302/2362336272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tiktok_clean["engagement_rate"] = tiktok_clean["likes"] / tiktok_clean["views"]
/tmp/ipykernel_302/2362336272.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tiktok_clean["engagement_rate"] = tiktok_clean["engagement_rate"] * 100
/tmp/ipykernel_302/2362336272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tiktok_clean["log_views"] = np.log1p(tiktok_clean["views"])
/tmp/ipykernel_302/2362336272.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tiktok_clean["log_likes"] = np.log1p(tiktok_clean["likes"])

In [24]:
tiktok_clean["duration_category"] = pd.qcut(
    tiktok_clean["duration"],
    q=3,
    labels=["short", "medium", "long"]
)

/tmp/ipykernel_302/1736333770.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tiktok_clean["duration_category"] = pd.qcut(

In [25]:
tiktok_clean.groupby("duration_category")["duration"].max()

/tmp/ipykernel_302/2654696130.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tiktok_clean.groupby("duration_category")["duration"].max()

duration_category
short     23
medium    42
long      60
Name: duration, dtype: int64

In [26]:
tiktok_clean

,video_id,views,likes,duration,engagement_rate,log_views,log_likes,duration_category
0,7017666017,343296.0,19425.0,59,5.658382,12.746351,9.874368,long
1,4014381136,140877.0,77355.0,32,54.909602,11.855650,11.256173,medium
2,9859838091,902185.0,97690.0,31,10.828156,13.712576,11.489565,medium
3,1866847991,437506.0,239954.0,25,54.845876,12.988848,12.388207,medium
4,7105231098,56167.0,34987.0,19,62.291025,10.936102,10.462760,short
...,...,...,...,...,...,...,...,...
19079,1492320297,6067.0,423.0,49,6.972144,8.710784,6.049733,long
19080,9841347807,2973.0,820.0,23,27.581567,7.997663,6.710523,short
19081,8024379946,734.0,102.0,50,13.896458,6.599870,4.634729,long
19082,7425795014,3394.0,655.0,8,19.298763,8.130059,6.486161,short
19083,4094655375,5034.0,815.0,58,16.189909,8.524169,6.704414,long